/*
 * THIS FILE IS AUTOMATICALLY GENERATED FROM THE FOLLOWING SEPCIFICATION FILES:
 *
 * - beats/app-logs/etc/fields.yml
 * - beats/request-metrics/etc/fields.yml
 *
 */

package com.sap.hcp.cf.logging.common;

public interface Fields {
    public String WRITTEN_AT = "written_at";
    public String WRITTEN_TS = "written_ts";
    public String CORRELATION_ID = "correlation_id";
    public String COMPONENT_ID = "component_id";
    public String COMPONENT_NAME = "component_name";
    public String COMPONENT_TYPE = "component_type";
    public String COMPONENT_INSTANCE = "component_instance";
    public String CONTAINER_ID = "container_id";
    public String ORGANIZATION_ID = "organization_id";
    public String ORGANIZATION_NAME = "organization_name";
    public String SPACE_ID = "space_id";
    public String SPACE_NAME = "space_name";
    public String LAYER = "layer";
    public String TYPE = "type";
    public String LOGGER = "logger";
    public String THREAD = "thread";
    public String LEVEL = "level";
    public String MSG = "msg";
    public String STACKTRACE = "stacktrace";
    public String CATEGORIES = "categories";
    public String CUSTOM_FIELDS = "custom_fields";
    public String REQUEST_ID = "request_id";
    public String REQUEST = "request";
    public String REQUEST_SENT_AT = "request_sent_at";
    public String REQUEST_RECEIVED_AT = "request_received_at";
    public String RESPONSE_SENT_AT = "response_sent_at";
    public String RESPONSE_RECEIVED_AT = "response_received_at";
    public String DIRECTION = "direction";
    public String RESPONSE_TIME_MS = "response_time_ms";
    public String PROTOCOL = "protocol";
    public String METHOD = "method";
    public String REMOTE_IP = "remote_ip";
    public String REMOTE_HOST = "remote_host";
    public String REMOTE_PORT = "remote_port";
    public String REMOTE_USER = "remote_user";
    public String REQUEST_SIZE_B = "request_size_b";
    public String RESPONSE_STATUS = "response_status";
    public String RESPONSE_SIZE_B = "response_size_b";
    public String RESPONSE_CONTENT_TYPE = "response_content_type";
    public String REFERER = "referer";
    public String X_FORWARDED_FOR = "x_forwarded_for";
}
